### ISSUE TITLE
Error while splitting slaves

### ISSUE THREAD

**Issue by lumirinc** [mdelgadoblasco/snap2stamps#10]
Hello Everyone,

While splitting slaves I am getting OSError: {Errno 13] Permission Denied. Any help would be appriciated. Kindly see complete log below.

(base) mirza@lumir:~/InSAR/Korea/Busan/2016/des/Project/bin$ python2 splitting_slaves.py project.conf 
/home/mirza/InSAR/Korea/Busan/2016/des/Project
/home/mirza/InSAR/Korea/Busan/2016/des/Project/graphs
IW2
/opt/snap/bin

#####################################################################

#####################################################################

[1] Folder: 20160108
/home/mirza/InSAR/Korea/Busan/2016/des/Project/slaves/20160108
['/home/mirza/InSAR/Korea/Busan/2016/des/Project/slaves/20160108/S1A_IW_SLC__1SDV_20160108T212412_20160108T212442_009408_00DA05_9248.zip']
FILE(s) : /home/mirza/InSAR/Korea/Busan/2016/des/Project/slaves/20160108/S1A_IW_SLC__1SDV_20160108T212412_20160108T212442_009408_00DA05_9248.zip
['/opt/snap/bin', '/home/mirza/InSAR/Korea/Busan/2016/des/Project/graphs/splitgraph2run.xml', '-c', '110', '-q', '16']
Traceback (most recent call last):
  File "splitting_slaves.py", line 121, in <module>
    process = subprocess.Popen(args, stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Comment by lumirinc** [comment]
I manage to resolve this issue. The issue was with gpt address in the configuration file. The address was not correct.
